<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class DishesTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {

        \DB::table('dishes')->delete();

        \DB::table('dishes')->insert([
            0 => [
                'id' => 1,
                'name' => 'Soep Ling Fa',
                'price' => '3.80',
                'description' => 'beschrijving',
                'type_id' => 1,
                'menu_number' => 1,
                'addition_id' => 1,
            ],
            1 => [
                'id' => 2,
                'name' => 'Kippensoep',
                'price' => '2.90',
                'description' => null,
                'type_id' => 1,
                'menu_number' => 2,
                'addition_id' => null,
            ],
            2 => [
                'id' => 3,
                'name' => 'Tomatensoep',
                'price' => '2.90',
                'description' => 'fsdfsdfsdf',
                'type_id' => 1,
                'menu_number' => 3,
                'addition_id' => null,
            ],
            3 => [
                'id' => 4,
                'name' => 'Haaienvinnensoep',
                'price' => '3.10',
                'description' => null,
                'type_id' => 1,
                'menu_number' => 4,
                'addition_id' => null,
            ],
            4 => [
                'id' => 5,
                'name' => 'Champignonsoep',
                'price' => '3.30',
                'description' => null,
                'type_id' => 1,
                'menu_number' => 5,
                'addition_id' => null,
            ],
            5 => [
                'id' => 6,
                'name' => 'Pekingsoep',
                'price' => '3.80',
                'description' => null,
                'type_id' => 1,
                'menu_number' => 6,
                'addition_id' => 1,
            ],
            6 => [
                'id' => 7,
                'name' => 'Wan Tan Soep',
                'price' => '4.30',
                'description' => null,
                'type_id' => 1,
                'menu_number' => 7,
                'addition_id' => null,
            ],
            7 => [
                'id' => 8,
                'name' => 'Chinese Champignonsoep',
                'price' => '4.10',
                'description' => null,
                'type_id' => 1,
                'menu_number' => 8,
                'addition_id' => null,
            ],
            8 => [
                'id' => 9,
                'name' => 'Loempia Ling Fa',
                'price' => '6.20',
                'description' => 'met atjar, ananas en pindasaus',
                'type_id' => 2,
                'menu_number' => 10,
                'addition_id' => null,
            ],
            9 => [
                'id' => 10,
                'name' => 'Loempia Compleet',
                'price' => '6.20',
                'description' => 'met gesmoord rundvlees en pikante saus',
                'type_id' => 2,
                'menu_number' => 11,
                'addition_id' => null,
            ],
            10 => [
                'id' => 11,
                'name' => 'Loempia met Kip',
                'price' => '3.90',
                'description' => null,
                'type_id' => 2,
                'menu_number' => 12,
                'addition_id' => null,
            ],
            11 => [
                'id' => 12,
                'name' => 'Loempia',
                'price' => '3.80',
                'description' => null,
                'type_id' => 2,
                'menu_number' => 13,
                'addition_id' => null,
            ],
            12 => [
                'id' => 13,
                'name' => 'Chinese mini loempia',
                'price' => '4.90',
                'description' => '4 st.',
                'type_id' => 2,
                'menu_number' => 14,
                'addition_id' => null,
            ],
            13 => [
                'id' => 14,
                'name' => 'Vegetarische mini loempia',
                'price' => '4.90',
                'description' => '12 st.',
                'type_id' => 2,
                'menu_number' => 14,
                'addition_id' => 1,
            ],
            14 => [
                'id' => 15,
                'name' => 'Kroepoek',
                'price' => '2.50',
                'description' => null,
                'type_id' => 2,
                'menu_number' => 15,
                'addition_id' => null,
            ],
            15 => [
                'id' => 16,
                'name' => 'Casave Kroepoek',
                'price' => '2.70',
                'description' => null,
                'type_id' => 2,
                'menu_number' => 15,
                'addition_id' => 1,
            ],
            16 => [
                'id' => 17,
                'name' => 'Pangsit Goreng',
                'price' => '3.90',
                'description' => '7 st.',
                'type_id' => 2,
                'menu_number' => 16,
                'addition_id' => null,
            ],
            17 => [
                'id' => 18,
                'name' => 'Pisang Goreng',
                'price' => '3.40',
                'description' => '5 st.',
                'type_id' => 2,
                'menu_number' => 17,
                'addition_id' => null,
            ],
            18 => [
                'id' => 19,
                'name' => 'Chinese Dim Sum',
                'price' => '5.40',
                'description' => 'mini loempia, kerry ko, pangsit goreng, garnalenpasteitje',
                'type_id' => 2,
                'menu_number' => 18,
                'addition_id' => null,
            ],
            19 => [
                'id' => 20,
                'name' => 'Sat&eacute; Babi',
                'price' => '5.40',
                'description' => '4 st.',
                'type_id' => 2,
                'menu_number' => 19,
                'addition_id' => null,
            ],
            20 => [
                'id' => 21,
                'name' => 'Sat&eacute; Ajam',
                'price' => '5.40',
                'description' => '4 st.',
                'type_id' => 2,
                'menu_number' => 20,
                'addition_id' => null,
            ],
            21 => [
                'id' => 22,
                'name' => 'Sat&eacute; Garnalen',
                'price' => '9.90',
                'description' => '3 st.',
                'type_id' => 2,
                'menu_number' => 20,
                'addition_id' => 1,
            ],
            22 => [
                'id' => 23,
                'name' => 'Fong Mei Ha',
                'price' => '8.10',
                'description' => 'krokant gepaneerd garnalen. 4 st.',
                'type_id' => 2,
                'menu_number' => 21,
                'addition_id' => null,
            ],
            23 => [
                'id' => 24,
                'name' => 'Patat',
                'price' => '2.30',
                'description' => null,
                'type_id' => 2,
                'menu_number' => 22,
                'addition_id' => null,
            ],
            24 => [
                'id' => 25,
                'name' => 'Tsa Siu Mai',
                'price' => '3.50',
                'description' => 'gebakken vleespasteitje. 4 st.',
                'type_id' => 2,
                'menu_number' => 23,
                'addition_id' => null,
            ],
            25 => [
                'id' => 26,
                'name' => 'Atjar',
                'price' => '3.00',
                'description' => null,
                'type_id' => 2,
                'menu_number' => 24,
                'addition_id' => null,
            ],
            26 => [
                'id' => 27,
                'name' => 'Witte Rijst',
                'price' => '3.00',
                'description' => null,
                'type_id' => 2,
                'menu_number' => 25,
                'addition_id' => null,
            ],
            27 => [
                'id' => 28,
                'name' => 'Grote pindasaus',
                'price' => '3.90',
                'description' => null,
                'type_id' => 2,
                'menu_number' => 26,
                'addition_id' => null,
            ],
            28 => [
                'id' => 29,
                'name' => 'Kleine pindasaus',
                'price' => '2.30',
                'description' => null,
                'type_id' => 2,
                'menu_number' => 27,
                'addition_id' => null,
            ],
            29 => [
                'id' => 30,
                'name' => 'Kippenpootje',
                'price' => '2.30',
                'description' => null,
                'type_id' => 2,
                'menu_number' => 28,
                'addition_id' => null,
            ],
            30 => [
                'id' => 31,
                'name' => 'Halve kip',
                'price' => '6.00',
                'description' => null,
                'type_id' => 2,
                'menu_number' => 29,
                'addition_id' => null,
            ],
            31 => [
                'id' => 32,
                'name' => 'Kroket',
                'price' => '1.40',
                'description' => null,
                'type_id' => 2,
                'menu_number' => 29,
                'addition_id' => 2,
            ],
            32 => [
                'id' => 33,
                'name' => 'Frikandel',
                'price' => '1.40',
                'description' => null,
                'type_id' => 2,
                'menu_number' => 29,
                'addition_id' => 3,
            ],
            33 => [
                'id' => 34,
                'name' => 'Kleine Sambal',
                'price' => '2.50',
                'description' => null,
                'type_id' => 2,
                'menu_number' => 180,
                'addition_id' => 2,
            ],
            34 => [
                'id' => 35,
                'name' => 'Bami of Nasi Goreng Ling Fa',
                'price' => '14.30',
                'description' => 'Foe Yong Hai, Babi Pangang, sat&eacute; en kippenpootje',
                'type_id' => 3,
                'menu_number' => 30,
                'addition_id' => null,
            ],
            35 => [
                'id' => 36,
                'name' => 'Bami of Nasi Goreng met ei',
                'price' => '5.00',
                'description' => null,
                'type_id' => 3,
                'menu_number' => 31,
                'addition_id' => null,
            ],
            36 => [
                'id' => 37,
                'name' => 'Bami of Nasi Goreng speciaal',
                'price' => '8.50',
                'description' => null,
                'type_id' => 3,
                'menu_number' => 32,
                'addition_id' => null,
            ],
            37 => [
                'id' => 38,
                'name' => 'Bami of Nasi Goreng met sat&eacute;',
                'price' => '8.50',
                'description' => '3 st.',
                'type_id' => 3,
                'menu_number' => 33,
                'addition_id' => null,
            ],
            38 => [
                'id' => 39,
                'name' => 'Nasi Yeung Chow',
                'price' => '10.90',
                'description' => null,
                'type_id' => 3,
                'menu_number' => 34,
                'addition_id' => null,
            ],
            39 => [
                'id' => 40,
                'name' => 'Nasi Yeung Chow',
                'price' => '13.00',
                'description' => 'met garnaaltjes en Cha Sieuw-vlees',
                'type_id' => 3,
                'menu_number' => 34,
                'addition_id' => 1,
            ],
            40 => [
                'id' => 41,
                'name' => 'Bami of Nasi Malay',
                'price' => '9.30',
                'description' => null,
                'type_id' => 3,
                'menu_number' => 35,
                'addition_id' => null,
            ],
            41 => [
                'id' => 42,
                'name' => 'Bami of Nasi met kipfilet',
                'price' => '9.30',
                'description' => null,
                'type_id' => 3,
                'menu_number' => 36,
                'addition_id' => null,
            ],
            42 => [
                'id' => 43,
                'name' => 'Bami of Nasi met varkensvlees',
                'price' => '9.30',
                'description' => null,
                'type_id' => 3,
                'menu_number' => 37,
                'addition_id' => null,
            ],
            43 => [
                'id' => 44,
                'name' => 'Bami of Nasi met garnalen',
                'price' => '14.30',
                'description' => null,
                'type_id' => 3,
                'menu_number' => 38,
                'addition_id' => null,
            ],
            44 => [
                'id' => 45,
                'name' => 'Bami of Nasi met ossenhaas',
                'price' => '15.30',
                'description' => null,
                'type_id' => 3,
                'menu_number' => 39,
                'addition_id' => null,
            ],
            45 => [
                'id' => 46,
                'name' => 'Babi Pangang, Foe Yong Hani en sat&eacute;',
                'price' => '15.80',
                'description' => null,
                'type_id' => 4,
                'menu_number' => 40,
                'addition_id' => null,
            ],
            46 => [
                'id' => 47,
                'name' => 'Babi Pangang, Tjap Tjoy en sat&eacute;',
                'price' => '15.80',
                'description' => null,
                'type_id' => 4,
                'menu_number' => 41,
                'addition_id' => null,
            ],
            47 => [
                'id' => 48,
                'name' => 'Babi Pangang, Koe Loe Yuk en sat&eacute;',
                'price' => '15.80',
                'description' => null,
                'type_id' => 4,
                'menu_number' => 42,
                'addition_id' => null,
            ],
            48 => [
                'id' => 49,
                'name' => 'Babi Pangang, Tau Sie Kai en sat&eacute;',
                'price' => '16.50',
                'description' => null,
                'type_id' => 4,
                'menu_number' => 43,
                'addition_id' => null,
            ],
            49 => [
                'id' => 50,
                'name' => 'Koe Loe Yuk, Foe Yong Hai en sat&eacute;',
                'price' => '15.80',
                'description' => null,
                'type_id' => 4,
                'menu_number' => 44,
                'addition_id' => null,
            ],
            50 => [
                'id' => 51,
                'name' => 'Koe Loe Yuk, Tjap Tjoy en sat&eacute;',
                'price' => '15.80',
                'description' => null,
                'type_id' => 4,
                'menu_number' => 45,
                'addition_id' => null,
            ],
            51 => [
                'id' => 52,
                'name' => 'Foe Yong Hai, Tjap Tjoy en sat&eacute;',
                'price' => '15.80',
                'description' => null,
                'type_id' => 4,
                'menu_number' => 46,
                'addition_id' => null,
            ],
            52 => [
                'id' => 53,
                'name' => 'Foe Yong Hai, Kip Kerrie en Sat&eacute;',
                'price' => '16.50',
                'description' => null,
                'type_id' => 4,
                'menu_number' => 47,
                'addition_id' => null,
            ],
            53 => [
                'id' => 54,
                'name' => 'Mihoen Ling Fa',
                'price' => '16.40',
                'description' => 'Foe Yong Hai, Babi Pangang, sat&eacute; en kippenpootje',
                'type_id' => 5,
                'menu_number' => 50,
                'addition_id' => null,
            ],
            54 => [
                'id' => 55,
                'name' => 'Mihoen met varkensvlees',
                'price' => '9.30',
                'description' => null,
                'type_id' => 5,
                'menu_number' => 51,
                'addition_id' => null,
            ],
            55 => [
                'id' => 56,
                'name' => 'Mihoen met kipfilet',
                'price' => '10.40',
                'description' => null,
                'type_id' => 5,
                'menu_number' => 52,
                'addition_id' => null,
            ],
            56 => [
                'id' => 57,
                'name' => 'Mihoen met ossenhaas',
                'price' => '16.40',
                'description' => null,
                'type_id' => 5,
                'menu_number' => 53,
                'addition_id' => null,
            ],
            57 => [
                'id' => 58,
                'name' => 'Mihoen met garnalen',
                'price' => '15.30',
                'description' => null,
                'type_id' => 5,
                'menu_number' => 54,
                'addition_id' => null,
            ],
            58 => [
                'id' => 59,
                'name' => 'Mihoen Singapore-style',
                'price' => '11.90',
                'description' => 'met kleine garnaaltjes en Cha Sieuw-vlees en kerrie poeder',
                'type_id' => 5,
                'menu_number' => 55,
                'addition_id' => null,
            ],
            59 => [
                'id' => 60,
                'name' => 'Mihoen met Cha Sieuw vlees',
                'price' => '11.20',
                'description' => null,
                'type_id' => 5,
                'menu_number' => 56,
                'addition_id' => null,
            ],
            60 => [
                'id' => 61,
                'name' => 'Chinese Bami Ling Fa',
                'price' => '16.90',
                'description' => 'Foe Yong Hai, Babi Pangang, sat&eacute; en kippenpootje',
                'type_id' => 6,
                'menu_number' => 57,
                'addition_id' => null,
            ],
            61 => [
                'id' => 62,
                'name' => 'Chinese Bami met varkensvlees',
                'price' => '10.10',
                'description' => null,
                'type_id' => 6,
                'menu_number' => 58,
                'addition_id' => null,
            ],
            62 => [
                'id' => 63,
                'name' => 'Chinese Bami met kipfilet',
                'price' => '11.20',
                'description' => null,
                'type_id' => 6,
                'menu_number' => 58,
                'addition_id' => 1,
            ],
            63 => [
                'id' => 64,
                'name' => 'Chinese Bami met Cha Sieuw-vlees',
                'price' => '12.20',
                'description' => null,
                'type_id' => 6,
                'menu_number' => 58,
                'addition_id' => 4,
            ],
            64 => [
                'id' => 65,
                'name' => 'Chinese Bami met garnalen',
                'price' => '15.80',
                'description' => null,
                'type_id' => 6,
                'menu_number' => 58,
                'addition_id' => 5,
            ],
            65 => [
                'id' => 66,
                'name' => 'Chinese Bami met ossenhaas',
                'price' => '17.40',
                'description' => null,
                'type_id' => 6,
                'menu_number' => 58,
                'addition_id' => 6,
            ],
            66 => [
                'id' => 67,
                'name' => 'Bami of Nasi Rames Ling Fa',
                'price' => '15.30',
                'description' => 'Babi Pangan, Foe Yong Hai, Daging Roedjak, Atjar en kippootje',
                'type_id' => 7,
                'menu_number' => null,
                'addition_id' => 7,
            ],
            67 => [
                'id' => 68,
                'name' => 'Bami of Nasi Rames',
                'price' => '8.80',
                'description' => null,
                'type_id' => 7,
                'menu_number' => null,
                'addition_id' => 8,
            ],
            68 => [
                'id' => 69,
                'name' => 'Bami of Nasi Rames speciaal',
                'price' => '10.80',
                'description' => null,
                'type_id' => 7,
                'menu_number' => null,
                'addition_id' => 9,
            ],
            69 => [
                'id' => 70,
                'name' => 'Gado Gado',
                'price' => '7.60',
                'description' => 'met witte rijst',
                'type_id' => 7,
                'menu_number' => null,
                'addition_id' => 10,
            ],
            70 => [
                'id' => 71,
                'name' => 'Daging Smoor',
                'price' => '13.30',
                'description' => 'met witte rijst',
                'type_id' => 7,
                'menu_number' => null,
                'addition_id' => 11,
            ],
            71 => [
                'id' => 72,
                'name' => 'Daging Roedjak',
                'price' => '13.30',
                'description' => 'met witte rijst',
                'type_id' => 7,
                'menu_number' => null,
                'addition_id' => 12,
            ],
            72 => [
                'id' => 73,
                'name' => 'Foe Yong Hai Ling Fa',
                'price' => '16.40',
                'description' => 'ossenhaas, garnalen en kipfilet',
                'type_id' => 8,
                'menu_number' => 59,
                'addition_id' => null,
            ],
            73 => [
                'id' => 74,
                'name' => 'Foe Yong Hai met varkensvlees',
                'price' => '8.80',
                'description' => null,
                'type_id' => 8,
                'menu_number' => 60,
                'addition_id' => null,
            ],
            74 => [
                'id' => 75,
                'name' => 'Foe Yong Hai met kipfilet',
                'price' => '9.20',
                'description' => null,
                'type_id' => 8,
                'menu_number' => 61,
                'addition_id' => null,
            ],
            75 => [
                'id' => 76,
                'name' => 'Foe Yong Hai met garnalen',
                'price' => '15.30',
                'description' => null,
                'type_id' => 8,
                'menu_number' => 62,
                'addition_id' => null,
            ],
            76 => [
                'id' => 77,
                'name' => 'Foe Yong Hai met krab',
                'price' => '15.30',
                'description' => null,
                'type_id' => 8,
                'menu_number' => 63,
                'addition_id' => null,
            ],
            77 => [
                'id' => 78,
                'name' => 'Foe Yong Hai met Cha Sieuw Vlees',
                'price' => '11.20',
                'description' => null,
                'type_id' => 8,
                'menu_number' => 63,
                'addition_id' => 1,
            ],
            78 => [
                'id' => 79,
                'name' => 'Foe Yong Hai met ossenhaas',
                'price' => '16.40',
                'description' => null,
                'type_id' => 8,
                'menu_number' => 63,
                'addition_id' => 4,
            ],
            79 => [
                'id' => 80,
                'name' => 'Tjap Tjoy Ling Fa',
                'price' => '16.40',
                'description' => 'ossenhaas, garnalen en kipfilet',
                'type_id' => 9,
                'menu_number' => 64,
                'addition_id' => null,
            ],
            80 => [
                'id' => 81,
                'name' => 'Tjap Tjoy met varkensvlees',
                'price' => '8.80',
                'description' => null,
                'type_id' => 9,
                'menu_number' => 65,
                'addition_id' => null,
            ],
            81 => [
                'id' => 82,
                'name' => 'Tjap Tjoy met kipfilet',
                'price' => '9.20',
                'description' => null,
                'type_id' => 9,
                'menu_number' => 66,
                'addition_id' => null,
            ],
            82 => [
                'id' => 83,
                'name' => 'Tjap Tjoy met ossenhaas',
                'price' => '16.40',
                'description' => null,
                'type_id' => 9,
                'menu_number' => 67,
                'addition_id' => null,
            ],
            83 => [
                'id' => 84,
                'name' => 'Tjap Tjoy met garnalen',
                'price' => '15.30',
                'description' => null,
                'type_id' => 9,
                'menu_number' => 68,
                'addition_id' => null,
            ],
            84 => [
                'id' => 85,
                'name' => 'Babi Pangang',
                'price' => '12.20',
                'description' => null,
                'type_id' => 10,
                'menu_number' => 70,
                'addition_id' => null,
            ],
            85 => [
                'id' => 86,
                'name' => 'Babi Pangang in ketjapsaus',
                'price' => '12.30',
                'description' => null,
                'type_id' => 10,
                'menu_number' => 71,
                'addition_id' => null,
            ],
            86 => [
                'id' => 87,
                'name' => 'Cha Sieuw',
                'price' => '13.30',
                'description' => 'rood geroosterd varkensvlees',
                'type_id' => 10,
                'menu_number' => 72,
                'addition_id' => null,
            ],
            87 => [
                'id' => 88,
                'name' => 'Cha Sieuw in pikante saus',
                'price' => '13.80',
                'description' => null,
                'type_id' => 10,
                'menu_number' => 73,
                'addition_id' => null,
            ],
            88 => [
                'id' => 89,
                'name' => 'Geroosterde speenvarken',
                'price' => '13.80',
                'description' => null,
                'type_id' => 10,
                'menu_number' => 74,
                'addition_id' => null,
            ],
            89 => [
                'id' => 90,
                'name' => 'Koe Loe Yuk',
                'price' => '11.90',
                'description' => 'bolletjes vlees met zoetzure saus',
                'type_id' => 10,
                'menu_number' => 75,
                'addition_id' => null,
            ],
            90 => [
                'id' => 91,
                'name' => 'Varkenshaas met kerriesaus',
                'price' => '11.90',
                'description' => null,
                'type_id' => 10,
                'menu_number' => 76,
                'addition_id' => null,
            ],
            91 => [
                'id' => 92,
                'name' => 'Varkenshaas met ketjapsaus',
                'price' => '11.90',
                'description' => null,
                'type_id' => 10,
                'menu_number' => 77,
                'addition_id' => null,
            ],
            92 => [
                'id' => 93,
                'name' => 'Varkenshaas met tomatensaus',
                'price' => '11.90',
                'description' => null,
                'type_id' => 10,
                'menu_number' => 78,
                'addition_id' => null,
            ],
            93 => [
                'id' => 94,
                'name' => 'Varkenshaas met champignons in knoflooksaus',
                'price' => '11.90',
                'description' => null,
                'type_id' => 10,
                'menu_number' => 78,
                'addition_id' => 1,
            ],
            94 => [
                'id' => 95,
                'name' => 'Varkenshaas met Chinese champignons',
                'price' => '12.20',
                'description' => null,
                'type_id' => 10,
                'menu_number' => 78,
                'addition_id' => 4,
            ],
            95 => [
                'id' => 96,
                'name' => 'Varkenshaas met zwarte bonensaus',
                'price' => '12.20',
                'description' => null,
                'type_id' => 10,
                'menu_number' => 79,
                'addition_id' => null,
            ],
            96 => [
                'id' => 97,
                'name' => 'Varkenshaas met verse ananas in zoetzure saus',
                'price' => '13.30',
                'description' => null,
                'type_id' => 10,
                'menu_number' => 79,
                'addition_id' => 1,
            ],
            97 => [
                'id' => 98,
                'name' => 'Yu Sian Yuk',
                'price' => '13.30',
                'description' => 'varkenshaas met licht zoet pikante kruiden saus',
                'type_id' => 10,
                'menu_number' => 79,
                'addition_id' => 4,
            ],
            98 => [
                'id' => 99,
                'name' => 'SzeChuan Yuk',
                'price' => '13.30',
                'description' => 'varkenshaas met pittige kruiden saus',
                'type_id' => 10,
                'menu_number' => 79,
                'addition_id' => 5,
            ],
            99 => [
                'id' => 100,
                'name' => 'Ajam Pangang',
                'price' => '13.00',
                'description' => null,
                'type_id' => 11,
                'menu_number' => 80,
                'addition_id' => null,
            ],
            100 => [
                'id' => 101,
                'name' => 'Ajam Pangang in ketjapsaus',
                'price' => '13.00',
                'description' => null,
                'type_id' => 11,
                'menu_number' => 81,
                'addition_id' => null,
            ],
            101 => [
                'id' => 102,
                'name' => 'Koe Loe Kai',
                'price' => '13.00',
                'description' => 'bolletjes kip met zoetzure saus',
                'type_id' => 11,
                'menu_number' => 82,
                'addition_id' => null,
            ],
            102 => [
                'id' => 103,
                'name' => 'Kipfilet met kerriesaus',
                'price' => '13.00',
                'description' => null,
                'type_id' => 11,
                'menu_number' => 83,
                'addition_id' => null,
            ],
            103 => [
                'id' => 104,
                'name' => 'Kipfilet met champignons in knoflooksaus',
                'price' => '13.00',
                'description' => null,
                'type_id' => 11,
                'menu_number' => 84,
                'addition_id' => null,
            ],
            104 => [
                'id' => 105,
                'name' => 'Kipfilet met tomatensaus',
                'price' => '13.00',
                'description' => null,
                'type_id' => 11,
                'menu_number' => 85,
                'addition_id' => null,
            ],
            105 => [
                'id' => 106,
                'name' => 'Kipfilet met ketjapsaus',
                'price' => '13.00',
                'description' => null,
                'type_id' => 11,
                'menu_number' => 86,
                'addition_id' => null,
            ],
            106 => [
                'id' => 107,
                'name' => 'Kipfilet met broccoli in knoflooksaus',
                'price' => '13.30',
                'description' => null,
                'type_id' => 11,
                'menu_number' => 87,
                'addition_id' => null,
            ],
            107 => [
                'id' => 108,
                'name' => 'Kipfilet met Chinese champignons',
                'price' => '13.30',
                'description' => null,
                'type_id' => 11,
                'menu_number' => 88,
                'addition_id' => null,
            ],
            108 => [
                'id' => 109,
                'name' => 'Kipfilet met zwarte pepersaus',
                'price' => '13.30',
                'description' => null,
                'type_id' => 11,
                'menu_number' => 89,
                'addition_id' => null,
            ],
            109 => [
                'id' => 110,
                'name' => 'Kipfilet met verse ananas in zoetzure saus',
                'price' => '13.30',
                'description' => null,
                'type_id' => 11,
                'menu_number' => 90,
                'addition_id' => null,
            ],
            110 => [
                'id' => 111,
                'name' => 'Kipfilet met zwarte pepersaus',
                'price' => '13.30',
                'description' => null,
                'type_id' => 11,
                'menu_number' => 91,
                'addition_id' => null,
            ],
            111 => [
                'id' => 112,
                'name' => 'Tjieuw Yem Kai',
                'price' => '13.30',
                'description' => 'licht gebraden kipfilet met zout en peper',
                'type_id' => 11,
                'menu_number' => 92,
                'addition_id' => null,
            ],
            112 => [
                'id' => 113,
                'name' => 'Yao Koe Kai',
                'price' => '13.30',
                'description' => 'kipfilet met cashewnoten in licht pikante saus',
                'type_id' => 11,
                'menu_number' => 93,
                'addition_id' => null,
            ],
            113 => [
                'id' => 114,
                'name' => 'Lychee Kai',
                'price' => '13.80',
                'description' => 'licht gebraden kipfilet met lychee in zoetzure saus',
                'type_id' => 11,
                'menu_number' => 94,
                'addition_id' => null,
            ],
            114 => [
                'id' => 115,
                'name' => 'Yu Sian Kai',
                'price' => '13.30',
                'description' => 'kipfilet met licht zoet pikante kruidensaus',
                'type_id' => 11,
                'menu_number' => 95,
                'addition_id' => null,
            ],
            115 => [
                'id' => 116,
                'name' => 'Sze Chuan Kai',
                'price' => '13.80',
                'description' => 'kipfilet met pittige kruidensaus',
                'type_id' => 11,
                'menu_number' => 96,
                'addition_id' => null,
            ],
            116 => [
                'id' => 117,
                'name' => 'Kung Bao Kai',
                'price' => '13.80',
                'description' => 'kipfilet met cashewnoten in pittige saus',
                'type_id' => 11,
                'menu_number' => 97,
                'addition_id' => null,
            ],
            117 => [
                'id' => 118,
                'name' => 'Garnalen met champignons in knoflooksaus',
                'price' => '15.90',
                'description' => null,
                'type_id' => 12,
                'menu_number' => 98,
                'addition_id' => null,
            ],
            118 => [
                'id' => 119,
                'name' => 'Garnalen met tomatensaus',
                'price' => '15.90',
                'description' => null,
                'type_id' => 12,
                'menu_number' => 99,
                'addition_id' => null,
            ],
            119 => [
                'id' => 120,
                'name' => 'Garnalen met ketjapsaus',
                'price' => '15.90',
                'description' => null,
                'type_id' => 12,
                'menu_number' => 100,
                'addition_id' => null,
            ],
            120 => [
                'id' => 121,
                'name' => 'Garnalen met broccoli',
                'price' => '16.10',
                'description' => null,
                'type_id' => 12,
                'menu_number' => 101,
                'addition_id' => null,
            ],
            121 => [
                'id' => 122,
                'name' => 'Garnalen met Chinese champignons',
                'price' => '16.10',
                'description' => null,
                'type_id' => 12,
                'menu_number' => 102,
                'addition_id' => null,
            ],
            122 => [
                'id' => 123,
                'name' => 'Garnalen met kerriesaus',
                'price' => '16.10',
                'description' => null,
                'type_id' => 12,
                'menu_number' => 103,
                'addition_id' => null,
            ],
            123 => [
                'id' => 124,
                'name' => 'Garnalen met zwarte bonensaus',
                'price' => '16.10',
                'description' => null,
                'type_id' => 12,
                'menu_number' => 104,
                'addition_id' => null,
            ],
            124 => [
                'id' => 125,
                'name' => 'Garnalen met zwarte pepersaus',
                'price' => '16.10',
                'description' => null,
                'type_id' => 12,
                'menu_number' => 105,
                'addition_id' => null,
            ],
            125 => [
                'id' => 126,
                'name' => 'Garnalen met chilisaus',
                'price' => '16.10',
                'description' => null,
                'type_id' => 12,
                'menu_number' => 106,
                'addition_id' => null,
            ],
            126 => [
                'id' => 127,
                'name' => 'Yu Sian Haa',
                'price' => '16.10',
                'description' => 'garnalen met licht zoet pikante kruidensaus',
                'type_id' => 12,
                'menu_number' => 107,
                'addition_id' => null,
            ],
            127 => [
                'id' => 128,
                'name' => 'Tjieuw Yem Haa',
                'price' => '16.10',
                'description' => 'licht gebraden garnalen met zout en peper',
                'type_id' => 12,
                'menu_number' => 108,
                'addition_id' => null,
            ],
            128 => [
                'id' => 129,
                'name' => 'Tja Tai Haa',
                'price' => '16.10',
                'description' => 'krokant gebakken garnalen',
                'type_id' => 12,
                'menu_number' => 109,
                'addition_id' => null,
            ],
            129 => [
                'id' => 130,
                'name' => 'Sze Chuan Haa',
                'price' => '16.40',
                'description' => null,
                'type_id' => 12,
                'menu_number' => 110,
                'addition_id' => null,
            ],
            130 => [
                'id' => 131,
                'name' => 'Ossenhaas met chanpignons in knoflooksaus',
                'price' => '16.90',
                'description' => null,
                'type_id' => 13,
                'menu_number' => 111,
                'addition_id' => null,
            ],
            131 => [
                'id' => 132,
                'name' => 'Ossenhaas met tomatensaus',
                'price' => '16.90',
                'description' => null,
                'type_id' => 13,
                'menu_number' => 112,
                'addition_id' => null,
            ],
            132 => [
                'id' => 133,
                'name' => 'Ossenhaas met ketjapsaus',
                'price' => '16.90',
                'description' => null,
                'type_id' => 13,
                'menu_number' => 113,
                'addition_id' => null,
            ],
            133 => [
                'id' => 134,
                'name' => 'Ossenhaas met broccoli',
                'price' => '17.10',
                'description' => null,
                'type_id' => 13,
                'menu_number' => 114,
                'addition_id' => null,
            ],
            134 => [
                'id' => 135,
                'name' => 'Ossenhaas met Chinese champignons',
                'price' => '17.10',
                'description' => null,
                'type_id' => 13,
                'menu_number' => 115,
                'addition_id' => null,
            ],
            135 => [
                'id' => 136,
                'name' => 'Ossenhaas met kerriesaus',
                'price' => '17.10',
                'description' => null,
                'type_id' => 13,
                'menu_number' => 116,
                'addition_id' => null,
            ],
            136 => [
                'id' => 137,
                'name' => 'Ossenhaas met zwarte bonensaus',
                'price' => '17.10',
                'description' => null,
                'type_id' => 13,
                'menu_number' => 117,
                'addition_id' => null,
            ],
            137 => [
                'id' => 138,
                'name' => 'Ossenhaas met zwarte pepersaus',
                'price' => '17.10',
                'description' => null,
                'type_id' => 13,
                'menu_number' => 118,
                'addition_id' => null,
            ],
            138 => [
                'id' => 139,
                'name' => 'Yu Sian Ngau Yuk',
                'price' => '17.10',
                'description' => 'ossenhaas met licht zoet pikante kruidensaus',
                'type_id' => 13,
                'menu_number' => 119,
                'addition_id' => null,
            ],
            139 => [
                'id' => 140,
                'name' => 'Sze Chuan Ngau Yuk',
                'price' => '17.40',
                'description' => 'ossenhaas met pittige kruidensaus',
                'type_id' => 13,
                'menu_number' => 120,
                'addition_id' => null,
            ],
            140 => [
                'id' => 141,
                'name' => 'Visfilet met kerriesaus',
                'price' => '14.50',
                'description' => null,
                'type_id' => 14,
                'menu_number' => 121,
                'addition_id' => null,
            ],
            141 => [
                'id' => 142,
                'name' => 'Visfilet met oestersaus',
                'price' => '14.50',
                'description' => null,
                'type_id' => 14,
                'menu_number' => 122,
                'addition_id' => null,
            ],
            142 => [
                'id' => 143,
                'name' => 'Visfilet met zoetzure saus',
                'price' => '14.50',
                'description' => 'licht gebraden visfilet in zoete pikante saus',
                'type_id' => 14,
                'menu_number' => 123,
                'addition_id' => null,
            ],
            143 => [
                'id' => 144,
                'name' => 'Hong Shau Yu',
                'price' => '14.50',
                'description' => 'licht gebraden visfilet in zoete pikante saus',
                'type_id' => 14,
                'menu_number' => 124,
                'addition_id' => null,
            ],
            144 => [
                'id' => 145,
                'name' => 'Tjeuw Yem Yu',
                'price' => '15.00',
                'description' => 'licht gebraden visfilet met zout en peper',
                'type_id' => 14,
                'menu_number' => 125,
                'addition_id' => null,
            ],
            145 => [
                'id' => 146,
                'name' => 'San Sching Po',
                'price' => '16.10',
                'description' => 'visfilet, garnalen, krab en groenten in knoflooksaus',
                'type_id' => 14,
                'menu_number' => 126,
                'addition_id' => null,
            ],
            146 => [
                'id' => 147,
                'name' => 'Geroosterde Peking Eend',
                'price' => '16.60',
                'description' => null,
                'type_id' => 15,
                'menu_number' => null,
                'addition_id' => 13,
            ],
            147 => [
                'id' => 148,
                'name' => 'Peking Eend met verse ananas in zoetzure saus',
                'price' => '17.10',
                'description' => null,
                'type_id' => 15,
                'menu_number' => null,
                'addition_id' => 14,
            ],
            148 => [
                'id' => 149,
                'name' => 'Peking Eend met Chinese champignons in oestersaus',
                'price' => '17.10',
                'description' => null,
                'type_id' => 15,
                'menu_number' => null,
                'addition_id' => 15,
            ],
            149 => [
                'id' => 150,
                'name' => 'Yu Sian Ya',
                'price' => '17.10',
                'description' => 'peking eend met licht zoet pikante kruidensaus',
                'type_id' => 15,
                'menu_number' => null,
                'addition_id' => 16,
            ],
            150 => [
                'id' => 151,
                'name' => 'Tiepan Ling Fa',
                'price' => '17.90',
                'description' => 'garnalen, kipfilet, ossenhaas en groenten in zwarte pepersaus',
                'type_id' => 16,
                'menu_number' => null,
                'addition_id' => 17,
            ],
            151 => [
                'id' => 152,
                'name' => 'Tiepan Kai',
                'price' => '15.30',
                'description' => 'licht gebraden kipfilet en groenten met zoet pikante saus',
                'type_id' => 16,
                'menu_number' => null,
                'addition_id' => 18,
            ],
            152 => [
                'id' => 153,
                'name' => 'Tiepan San Yuk',
                'price' => '17.10',
                'description' => 'lichtgrbaden varkenshaas, kipfilet, ossenhaas en groenten met zoet pikante saus',
                'type_id' => 16,
                'menu_number' => null,
                'addition_id' => 19,
            ],
            153 => [
                'id' => 154,
                'name' => 'Tiepan Haa',
                'price' => '17.40',
                'description' => 'garnalen en groenten met zoet pikante saus',
                'type_id' => 16,
                'menu_number' => null,
                'addition_id' => 20,
            ],
            154 => [
                'id' => 155,
                'name' => 'Tiepan Ngau Yuk',
                'price' => '19.50',
                'description' => '5st. ossenhaas en groenten met zoet pikante saus',
                'type_id' => 16,
                'menu_number' => null,
                'addition_id' => 21,
            ],
            155 => [
                'id' => 156,
                'name' => 'Tau Fu Po',
                'price' => '15.30',
                'description' => 'sojakaas, cha sieuw garnalen en chinese paddenstoelen',
                'type_id' => 16,
                'menu_number' => null,
                'addition_id' => 22,
            ],
            156 => [
                'id' => 157,
                'name' => 'Vegetarische Tjap Tjoy',
                'price' => '8.30',
                'description' => null,
                'type_id' => 17,
                'menu_number' => null,
                'addition_id' => 23,
            ],
            157 => [
                'id' => 158,
                'name' => 'Lo Han Zhai',
                'price' => '11.20',
                'description' => 'sojakaas, Chinese paddenstoelen en groenten in knoflooksaus',
                'type_id' => 17,
                'menu_number' => null,
                'addition_id' => 24,
            ],
            158 => [
                'id' => 159,
                'name' => 'Vegetarische Foe Yong Hai',
                'price' => '8.30',
                'description' => null,
                'type_id' => 17,
                'menu_number' => null,
                'addition_id' => 25,
            ],
            159 => [
                'id' => 160,
                'name' => 'Frites, sat&eacute; (2st.) en ei',
                'price' => '6.50',
                'description' => null,
                'type_id' => 18,
                'menu_number' => null,
                'addition_id' => 26,
            ],
            160 => [
                'id' => 161,
                'name' => 'Frites, kippootje en ei',
                'price' => '6.50',
                'description' => null,
                'type_id' => 18,
                'menu_number' => null,
                'addition_id' => 27,
            ],
            161 => [
                'id' => 162,
                'name' => 'Frites, mini loempia (2st.) en ei',
                'price' => '6.50',
                'description' => null,
                'type_id' => 18,
                'menu_number' => null,
                'addition_id' => 28,
            ],
            162 => [
                'id' => 163,
                'name' => 'Kinder Bami of Nasi met sat&eacute; (2st.) en ei',
                'price' => '6.50',
                'description' => null,
                'type_id' => 18,
                'menu_number' => null,
                'addition_id' => 29,
            ],
            163 => [
                'id' => 164,
                'name' => 'Indische rijsttafel (voor 1 persoon)',
                'price' => '16.40',
                'description' => 'Gado gado, Foe Yong Hai, sat&eacute;, Daging Roedjak, Daging Smoor, Ajam Ketjap, Atjar, Pisang Goreng, Pindas en Cocos',
                'type_id' => 19,
                'menu_number' => null,
                'addition_id' => 30,
            ],
            164 => [
                'id' => 165,
                'name' => 'Indische rijsttafel<br>Vanaf 2 personen... Per persoon',
                'price' => '15.00',
                'description' => 'Ajam Ketjap, Gado Gado, Daging Smoor, Kroepoek, Daging Roedjak, Foe Yong Hai, Sat&eacute;, Sambal Goreng Boontjes, Sambal Goreng Kering, Atjar, Pisang Goreng, Pinda en Cocos',
                'type_id' => 19,
                'menu_number' => null,
                'addition_id' => 31,
            ],
            165 => [
                'id' => 167,
                'name' => 'Chinese Indische Rijsttafel<br>Vanaf 4 personen... per persoon',
                'price' => '16.50',
                'description' => 'Foe Yong Hai, Babi Pangang, Tjap Tjoy, Koe Loe Yuk, Ajam Ketjap, Daging Smoor, Daging Roedjak, Sat&eacute;, Ei, Kroepoek, Sambal Goeren boontjes, Atjar, Pisang Goreng, Pinda en Cocos',
                'type_id' => 19,
                'menu_number' => null,
                'addition_id' => 32,
            ],
            166 => [
                'id' => 168,
                'name' => 'Chinese Rijsttafel<br>Vanaf 2 personen... per persoon',
                'price' => '17.00',
                'description' => 'Kippen- of Tomatensoep, Tjap Tjoy met kipfilet, Koe Loe Yuk, Gebakken garnalen, Babi Pangang, Foe Yong Hai, sat&eacute;, kroepoek',
                'type_id' => 19,
                'menu_number' => null,
                'addition_id' => 33,
            ],
            167 => [
                'id' => 169,
                'name' => 'Kantones Rijsttafel<br>Vanaf 2 personen... per persoon',
                'price' => '23.00',
                'description' => 'Wan Tan soep, Chinese Dim Sum (mini loempia, kerrie ko, pangsit goreng, garnalen, pasteitje), Geroosterde Peking Eend, Lychee Kai (licht gebraden kipfilet met lychee in zoetzure saus), Tau Sie Haa (garnalen met zwarte bonensaus)',
                'type_id' => 19,
                'menu_number' => null,
                'addition_id' => 34,
            ],
            168 => [
                'id' => 170,
                'name' => 'Sze Chuan Rijsttafel<br>Vanaf 2 personen... per persoon',
                'price' => '23.00',
                'description' => 'Peking Soep (pittige lichtzure soep), Chinese Dim Sum (mini loempia, kerrie ko, pangsit goreng, garnalen, pastei(tje), Tjieuw Yem Kai (licht gebakken kipfilet met zout en peper), Lychee Yuk (licht gebraden varkensvlees met lychee in zoetzure saus), Yu Sia',
                'type_id' => 19,
                'menu_number' => null,
                'addition_id' => 35,
            ],
            169 => [
                'id' => 171,
                'name' => 'Buffet Menu A, per persoon',
                'price' => '12.80',
                'description' => 'Mini Loempia\'s, Pisang Goreng, Babi Pangang, Koe Loe Yuk, Foe Yong Hai, Kipfilet met zwarte bonensaus, Tjap Tjoy met kipfilet, sat&eacute; Ajam',
                'type_id' => 20,
                'menu_number' => null,
                'addition_id' => null,
            ],
            170 => [
                'id' => 172,
                'name' => 'Buffet Menu B, per persoon',
                'price' => '15.00',
                'description' => 'Mini Loempia\'s, Pisang Goreng, Babi Pangang, Foe Yong Hai, Kung Bao Kai, Hong Shau Yu, sat&eacute; Ajam, Ossenhaas met zwarte bonensaus, Kipfilet met kerriesaus',
                'type_id' => 20,
                'menu_number' => null,
                'addition_id' => null,
            ],
            171 => [
                'id' => 173,
                'name' => 'Bami of Nasi Goreng ipv rijst',
                'price' => '0.90',
                'description' => null,
                'type_id' => 21,
                'menu_number' => null,
                'addition_id' => null,
            ],
            172 => [
                'id' => 174,
                'name' => 'Mihoen Goreng ipv rijst',
                'price' => '2.50',
                'description' => null,
                'type_id' => 21,
                'menu_number' => null,
                'addition_id' => null,
            ],
            173 => [
                'id' => 175,
                'name' => 'Chinese Bami ipv rijst',
                'price' => '2.50',
                'description' => null,
                'type_id' => 21,
                'menu_number' => null,
                'addition_id' => null,
            ],
        ]);

    }
}
